In [3]:
import pandas as pd
df = pd.read_json("G:\Project\BrickView\Scripts\listings.json")
df.head()

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6184\3868529625.py:2: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_json("G:\Project\BrickView\Scripts\listings.json")

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [4]:
df.isnull().sum()

Listing_ID       0
City             0
Property_Type    0
Price            0
Sqft             0
Date_Listed      0
Agent_ID         0
Latitude         0
Longitude        0
dtype: int64

In [5]:
df.dtypes

Listing_ID           str
City                 str
Property_Type        str
Price            float64
Sqft             float64
Date_Listed          str
Agent_ID             str
Latitude         float64
Longitude        float64
dtype: object

In [6]:
df["Date_Listed"] = pd.to_datetime(df["Date_Listed"])

In [7]:
df.dtypes

Listing_ID                  str
City                        str
Property_Type               str
Price                   float64
Sqft                    float64
Date_Listed      datetime64[us]
Agent_ID                    str
Latitude                float64
Longitude               float64
dtype: object

In [8]:
df1 = pd.read_json("G:\Project\BrickView\Scripts\property.json")
df1.head()

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6184\2661670123.py:1: SyntaxWarning: invalid escape sequence '\P'
  df1 = pd.read_json("G:\Project\BrickView\Scripts\property.json")

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [9]:
df1.dtypes

attribute_id           int64
listing_id               str
bedrooms               int64
bathrooms              int64
floor_number           int64
total_floors           int64
year_built             int64
is_rented               bool
tenant_count           int64
furnishing_status        str
metro_distance_km    float64
parking_available       bool
power_backup            bool
dtype: object

In [10]:
df1.isnull().sum()

attribute_id         0
listing_id           0
bedrooms             0
bathrooms            0
floor_number         0
total_floors         0
year_built           0
is_rented            0
tenant_count         0
furnishing_status    0
metro_distance_km    0
parking_available    0
power_backup         0
dtype: int64

In [12]:
df2 = pd.read_json("G:\Project\BrickView\Scripts\Agents.json")
df2.head()

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6184\3562600013.py:1: SyntaxWarning: invalid escape sequence '\P'
  df2 = pd.read_json("G:\Project\BrickView\Scripts\Agents.json")

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

In [13]:
df2.dtypes

Agent_ID                str
Name                    str
Phone                   str
Email                   str
commission_rate     float64
deals_closed          int64
rating              float64
experience_years      int64
avg_closing_days      int64
dtype: object

In [14]:
df.isnull().sum()

Listing_ID       0
City             0
Property_Type    0
Price            0
Sqft             0
Date_Listed      0
Agent_ID         0
Latitude         0
Longitude        0
dtype: int64

In [15]:
df3= pd.read_json("G:\Project\BrickView\Scripts\Buyers.json")
df3.head()

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6184\2726933321.py:1: SyntaxWarning: invalid escape sequence '\P'
  df3= pd.read_json("G:\Project\BrickView\Scripts\Buyers.json")

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,NaN,0
1,2,L00866,Investor,Cheque,False,NaN,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,NaN,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [16]:
df3.dtypes

buyer_id         int64
sale_id            str
buyer_type         str
payment_mode       str
loan_taken        bool
loan_provider      str
loan_amount      int64
dtype: object

In [17]:
df3.isnull().sum()

buyer_id            0
sale_id             0
buyer_type          0
payment_mode        0
loan_taken          0
loan_provider    9966
loan_amount         0
dtype: int64

In [19]:
df3["loan_provider"] = df3["loan_provider"].fillna("No Loan")

In [20]:
df3.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,No Loan,0
1,2,L00866,Investor,Cheque,False,No Loan,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,No Loan,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [21]:
df3.isnull().sum()

buyer_id         0
sale_id          0
buyer_type       0
payment_mode     0
loan_taken       0
loan_provider    0
loan_amount      0
dtype: int64

In [23]:
df4=pd.read_csv("G:\Project\BrickView\Scripts\sales.csv")
df4.head()

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6184\2404092773.py:1: SyntaxWarning: invalid escape sequence '\P'
  df4=pd.read_csv("G:\Project\BrickView\Scripts\sales.csv")

  Listing_ID    Sale_Price   Date_Sold  Days_on_Market
0     L01179  9.255800e+05  2023-07-07       65.005560
1     L00866  1.054160e+05  2023-06-14       38.004620
2     L00102  1.825184e+06  2023-09-09       22.992622
3     L00440  1.932085e+06  2023-10-29       72.012274
4     L00059  7.765860e+05  2023-05-01      116.000152

In [24]:
df4.dtypes

Listing_ID            str
Sale_Price        float64
Date_Sold             str
Days_on_Market    float64
dtype: object

In [26]:
df4["Date_Sold"] = pd.to_datetime(df4["Date_Sold"])

In [27]:
df4.dtypes

Listing_ID                   str
Sale_Price               float64
Date_Sold         datetime64[us]
Days_on_Market           float64
dtype: object

In [28]:
df4.isnull().sum()

Listing_ID        0
Sale_Price        0
Date_Sold         0
Days_on_Market    0
dtype: int64

In [36]:
df3.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,No Loan,0
1,2,L00866,Investor,Cheque,False,No Loan,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,No Loan,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [38]:
df4.dtypes

Listing_ID                   str
Sale_Price               float64
Date_Sold         datetime64[us]
Days_on_Market           float64
dtype: object

In [39]:
df3.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,No Loan,0
1,2,L00866,Investor,Cheque,False,No Loan,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,No Loan,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [47]:
df3["loan_taken"] = df3["loan_taken"].replace({
    True : 1,
    False: 0
})

In [48]:
df3

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,0,No Loan,0
1,2,L00866,Investor,Cheque,0,No Loan,0
2,3,L00102,Investor,Cheque,1,Axis,2317757
3,4,L00440,Investor,Bank Transfer,0,No Loan,0
4,5,L00059,Investor,UPI,1,HDFC,4191221
...,...,...,...,...,...,...,...
19995,19996,L00891,Investor,UPI,0,No Loan,0
19996,19997,L00834,End User,UPI,0,No Loan,0
19997,19998,L01188,Investor,UPI,0,No Loan,0
19998,19999,L00905,Investor,Cheque,1,ICICI,3701968
19999,20000,L00526,Investor,Cash,1,SBI,3805678

In [49]:
df1.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [50]:
df1["parking_available"] = df1["parking_available"].replace({
    True : 1,
    False: 0
})

In [51]:
df1["is_rented"] = df1["is_rented"].replace({
    True : 1,
    False: 0
})

In [53]:
df1.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,1,4,Furnished,7.26,0,1
1,2,L00002,2,2,19,29,2020,0,0,Unfurnished,4.84,1,0
2,3,L00003,2,3,8,26,2007,1,4,Semi-Furnished,4.92,0,0
3,4,L00004,3,3,25,10,2003,0,3,Furnished,1.20,0,1
4,5,L00005,2,2,15,16,2008,1,1,Semi-Furnished,7.90,0,0

In [52]:
df1["power_backup"] = df1["power_backup"].replace({
    True : 1,
    False: 0
})